export interface Gym {
  id: number
  name: string
  subtitle: string
  badgeColor: string
  badgeIcon: string[] // 8x8 pixel grid
  requiredDrinks: number // drinks to log here before badge
  specialty: string
}

export const GYMS: Gym[] = [
  {
    id: 1,
    name: "The Frothy Mug",
    subtitle: "Lager Den",
    badgeColor: "#c28b4a",
    requiredDrinks: 1,
    specialty: "Beer",
    badgeIcon: [
      "..####..",
      ".#.aa.#.",
      ".#.aa.#.",
      ".######.",
      ".#....#.",
      ".######.",
      "..####..",
      "........",
    ],
  },
  {
    id: 2,
    name: "Ember Shots",
    subtitle: "Fire Parlour",
    badgeColor: "#e43b44",
    requiredDrinks: 1,
    specialty: "Shot",
    badgeIcon: [
      "...##...",
      "..#aa#..",
      ".#.aa.#.",
      ".#....#.",
      "..#..#..",
      "...##...",
      "...##...",
      "........",
    ],
  },
  {
    id: 3,
    name: "Rosegarden",
    subtitle: "Fairy Bistro",
    badgeColor: "#f4a4c0",
    requiredDrinks: 1,
    specialty: "Wine",
    badgeIcon: [
      "..####..",
      ".#.aa.#.",
      ".#.aa.#.",
      "..#..#..",
      "...##...",
      "...##...",
      "..####..",
      "........",
    ],
  },
  {
    id: 4,
    name: "Clear Springs",
    subtitle: "Hydro Bar",
    badgeColor: "#63c6e1",
    requiredDrinks: 1,
    specialty: "Water",
    badgeIcon: [
      "...##...",
      "..#aa#..",
      ".#.aa.#.",
      ".#.aa.#.",
      ".#....#.",
      "..#..#..",
      "...##...",
      "........",
    ],
  },
  {
    id: 5,
    name: "The Shaker",
    subtitle: "Mix Lounge",
    badgeColor: "#63c74d",
    requiredDrinks: 1,
    specialty: "Cocktail",
    badgeIcon: [
      "#......#",
      ".#.##.#.",
      "..#aa#..",
      "..#aa#..",
      "...##...",
      "...##...",
      "..####..",
      "........",
    ],
  },
  {
    id: 6,
    name: "Barrel & Cask",
    subtitle: "Aged Cellar",
    badgeColor: "#c28b4a",
    requiredDrinks: 2,
    specialty: "Beer",
    badgeIcon: [
      ".######.",
      "#.#aa#.#",
      "#.#aa#.#",
      "#.####.#",
      "#.#..#.#",
      "#.####.#",
      ".######.",
      "........",
    ],
  },
  {
    id: 7,
    name: "Inferno Lounge",
    subtitle: "Blaze Chamber",
    badgeColor: "#e43b44",
    requiredDrinks: 2,
    specialty: "Shot",
    badgeIcon: [
      "...##...",
      "..#aa#..",
      ".#.aa.#.",
      "#..aa..#",
      ".#.aa.#.",
      "..#aa#..",
      "...##...",
      "........",
    ],
  },
  {
    id: 8,
    name: "Chateau Violet",
    subtitle: "Grand Vineyard",
    badgeColor: "#f4a4c0",
    requiredDrinks: 2,
    specialty: "Wine",
    badgeIcon: [
      "..####..",
      ".#.aa.#.",
      "#..aa..#",
      "#..aa..#",
      ".#.aa.#.",
      "..#..#..",
      "..####..",
      "........",
    ],
  },
  {
    id: 9,
    name: "Tidal Tavern",
    subtitle: "Deep Reef",
    badgeColor: "#63c6e1",
    requiredDrinks: 2,
    specialty: "Water",
    badgeIcon: [
      "###..###",
      "#.#aa#.#",
      ".#.aa.#.",
      "..#aa#..",
      ".#.aa.#.",
      "#.#..#.#",
      "###..###",
      "........",
    ],
  },
  {
    id: 10,
    name: "Botanica",
    subtitle: "Jungle Lab",
    badgeColor: "#63c74d",
    requiredDrinks: 2,
    specialty: "Cocktail",
    badgeIcon: [
      "..#..#..",
      ".##aa##.",
      "#..aa..#",
      "########",
      "#..aa..#",
      ".##aa##.",
      "..#..#..",
      "........",
    ],
  },
]

export const MASTER_TOURNAMENT = {
  id: 11,
  name: "The Grand Pub League",
  subtitle: "Master Tournament",
  badgeColor: "#e8c170",
  specialty: "All Types",
}
