export interface Gym {
  id: number
  name: string
  subtitle: string
  badgeColor: string
  badgeSprite: string // Path to 16x16 badge sprite
  requiredDrinks: number // drinks to log here before badge
  specialty: string
  leaderName: string
  badgeName: string
  pub: string
  address: string
}

export const GYMS: Gym[] = [
  {
    id: 1,
    name: "The Frothy Mug",
    subtitle: "Lager Den",
    badgeColor: "#c28b4a",
    badgeSprite: "/gyms/Normal.png",
    requiredDrinks: 1,
    specialty: "Beer",
    leaderName: "BROCK",
    badgeName: "Boulder Badge",
    pub: "The Frothy Mug",
    address: "12 Pewter Lane, Boulder District",
  },
  {
    id: 2,
    name: "Ember Shots",
    subtitle: "Fire Parlour",
    badgeColor: "#e43b44",
    badgeSprite: "/gyms/Ghost.png",
    requiredDrinks: 1,
    specialty: "Shot",
    leaderName: "BLAZE",
    badgeName: "Ember Badge",
    pub: "Ember Shots Bar",
    address: "45 Cinnabar Street, Volcano Quarter",
  },
  {
    id: 3,
    name: "Rosegarden",
    subtitle: "Fairy Bistro",
    badgeColor: "#f4a4c0",
    badgeSprite: "/gyms/Grass.png",
    requiredDrinks: 1,
    specialty: "Wine",
    leaderName: "ERIKA",
    badgeName: "Rainbow Badge",
    pub: "Rosegarden Bistro",
    address: "8 Celadon Avenue, Garden District",
  },
  {
    id: 4,
    name: "Clear Springs",
    subtitle: "Hydro Bar",
    badgeColor: "#63c6e1",
    badgeSprite: "/gyms/Water.png",
    requiredDrinks: 1,
    specialty: "Water",
    leaderName: "MISTY",
    badgeName: "Cascade Badge",
    pub: "Clear Springs Bar",
    address: "23 Cerulean Way, Waterfront",
  },
  {
    id: 5,
    name: "The Shaker",
    subtitle: "Mix Lounge",
    badgeColor: "#63c74d",
    badgeSprite: "/gyms/Ice.png",
    requiredDrinks: 1,
    specialty: "Cocktail",
    leaderName: "MIXIE",
    badgeName: "Mix Badge",
    pub: "The Shaker Lounge",
    address: "67 Saffron Plaza, Downtown",
  },
  {
    id: 6,
    name: "Barrel & Cask",
    subtitle: "Aged Cellar",
    badgeColor: "#c28b4a",
    badgeSprite: "/gyms/Bug.png",
    requiredDrinks: 2,
    specialty: "Beer",
    leaderName: "BRUCE",
    badgeName: "Barrel Badge",
    pub: "Barrel & Cask Cellar",
    address: "89 Vermillion Road, Old Town",
  },
  {
    id: 7,
    name: "Inferno Lounge",
    subtitle: "Blaze Chamber",
    badgeColor: "#e43b44",
    badgeSprite: "/gyms/Electric.png",
    requiredDrinks: 2,
    specialty: "Shot",
    leaderName: "LT. SURGE",
    badgeName: "Thunder Badge",
    pub: "Inferno Lounge",
    address: "34 Electric Avenue, Power Plant",
  },
  {
    id: 8,
    name: "Chateau Violet",
    subtitle: "Grand Vineyard",
    badgeColor: "#f4a4c0",
    badgeSprite: "/gyms/Psychic.png",
    requiredDrinks: 2,
    specialty: "Wine",
    leaderName: "VIOLET",
    badgeName: "Violet Badge",
    pub: "Chateau Violet",
    address: "156 Lavender Heights, Wine Country",
  },
  {
    id: 9,
    name: "Tidal Tavern",
    subtitle: "Deep Reef",
    badgeColor: "#63c6e1",
    badgeSprite: "/gyms/Water.png",
    requiredDrinks: 2,
    specialty: "Water",
    leaderName: "MARINA",
    badgeName: "Soul Badge",
    pub: "Tidal Tavern",
    address: "99 Fuchsia Pier, Harbor District",
  },
  {
    id: 10,
    name: "Botanica",
    subtitle: "Jungle Lab",
    badgeColor: "#63c74d",
    badgeSprite: "/gyms/Grass.png",
    requiredDrinks: 2,
    specialty: "Cocktail",
    leaderName: "FLORA",
    badgeName: "Earth Badge",
    pub: "Botanica Lab",
    address: "7 Viridian Grove, Forest Edge",
  },
]

export const MASTER_TOURNAMENT = {
  id: 11,
  name: "The Grand Pub League",
  subtitle: "Master Tournament",
  badgeColor: "#e8c170",
  specialty: "All Types",
}
